In [ ]:
import pandas as pd
df=pd.read_csv("cardata.csv")
print(df)

    manufacturer   model  displ  year  cyl       trans drv  cty  hwy fl  \
0           audi      a4    1.8  1999    4    auto(l5)   f   18   29  p
1           audi      a4    1.8  1999    4  manual(m5)   f   21   29  p
2           audi      a4    2.0  2008    4  manual(m6)   f   20   31  p
3           audi      a4    2.0  2008    4    auto(av)   f   21   30  p
4           audi      a4    2.8  1999    6    auto(l5)   f   16   26  p
..           ...     ...    ...   ...  ...         ...  ..  ...  ... ..
229   volkswagen  passat    2.0  2008    4    auto(s6)   f   19   28  p
230   volkswagen  passat    2.0  2008    4  manual(m6)   f   21   29  p
231   volkswagen  passat    2.8  1999    6    auto(l5)   f   16   26  p
232   volkswagen  passat    2.8  1999    6  manual(m5)   f   18   26  p
233   volkswagen  passat    3.6  2008    6    auto(s6)   f   17   26  p

       class
0    compact
1    compact
2    compact
3    compact
4    compact
..       ...
229  midsize
230  midsize
231  midsize
232  midsize
233  midsize

[234 rows x 11 columns]

In [ ]:
empty_rows = df.isnull().all(axis=1)
print(empty_rows)
num_empty_rows = empty_rows.sum()
print("Number of empty rows:", num_empty_rows)

0      False
1      False
2      False
3      False
4      False
       ...
229    False
230    False
231    False
232    False
233    False
Length: 234, dtype: bool
Number of empty rows: 0

In [ ]:
missing_values_in_row = df.isnull().any(axis=1)
print(df[missing_values_in_row])
num_missing_values_in_row = missing_values_in_row.sum()
print("Number of rows with missing values:", num_missing_values_in_row)

Empty DataFrame
Columns: [manufacturer, model, displ, year, cyl, trans, drv, cty, hwy, fl, class]
Index: []
Number of rows with missing values: 0

In [ ]:
df_cleaner = df.dropna()
print(df_cleaner)

    manufacturer   model  displ  year  cyl       trans drv  cty  hwy fl  \
0           audi      a4    1.8  1999    4    auto(l5)   f   18   29  p
1           audi      a4    1.8  1999    4  manual(m5)   f   21   29  p
2           audi      a4    2.0  2008    4  manual(m6)   f   20   31  p
3           audi      a4    2.0  2008    4    auto(av)   f   21   30  p
4           audi      a4    2.8  1999    6    auto(l5)   f   16   26  p
..           ...     ...    ...   ...  ...         ...  ..  ...  ... ..
229   volkswagen  passat    2.0  2008    4    auto(s6)   f   19   28  p
230   volkswagen  passat    2.0  2008    4  manual(m6)   f   21   29  p
231   volkswagen  passat    2.8  1999    6    auto(l5)   f   16   26  p
232   volkswagen  passat    2.8  1999    6  manual(m5)   f   18   26  p
233   volkswagen  passat    3.6  2008    6    auto(s6)   f   17   26  p

       class
0    compact
1    compact
2    compact
3    compact
4    compact
..       ...
229  midsize
230  midsize
231  midsize
232  midsize
233  midsize

[234 rows x 11 columns]

In [ ]:
df2=pd.read_csv("biostats.csv")

In [ ]:
sorted_df = df2.sort_values(by='Name')
print(sorted_df)

    Name Sex  Age  Height  Weigth
0   Alex   M   41      74     170
1   Bert   M   42      68     166
2   Carl   M   32      70     155
3   Dave   M   39      72     167
4   Elly   F   30      66     124
5   Fran   F   33      66     115
6   Gwen   F   26      64     121
7   Hank   M   30      71     158
8   Ivan   M   53      72     175
9   Jake   M   32      69     143
10  Kate   F   47      69     139
11  Luke   M   34      72     163
12  Myra   F   23      62      98
13  Neil   M   36      75     160
14  Omar   M   38      70     145
15  Page   F   31      67     135
16  Quin   M   29      71     176
17  Ruth   F   28      65     131

In [ ]:
sorted_df = df2.sort_values(by='Name', ascending=False)
print(sorted_df)

    Name Sex  Age  Height  Weigth
17  Ruth   F   28      65     131
16  Quin   M   29      71     176
15  Page   F   31      67     135
14  Omar   M   38      70     145
13  Neil   M   36      75     160
12  Myra   F   23      62      98
11  Luke   M   34      72     163
10  Kate   F   47      69     139
9   Jake   M   32      69     143
8   Ivan   M   53      72     175
7   Hank   M   30      71     158
6   Gwen   F   26      64     121
5   Fran   F   33      66     115
4   Elly   F   30      66     124
3   Dave   M   39      72     167
2   Carl   M   32      70     155
1   Bert   M   42      68     166
0   Alex   M   41      74     170

In [ ]:
filtered_df = df2[df2['Height'] > 30]
print(filtered_df)

    Name Sex  Age  Height  Weigth
0   Alex   M   41      74     170
1   Bert   M   42      68     166
2   Carl   M   32      70     155
3   Dave   M   39      72     167
4   Elly   F   30      66     124
5   Fran   F   33      66     115
6   Gwen   F   26      64     121
7   Hank   M   30      71     158
8   Ivan   M   53      72     175
9   Jake   M   32      69     143
10  Kate   F   47      69     139
11  Luke   M   34      72     163
12  Myra   F   23      62      98
13  Neil   M   36      75     160
14  Omar   M   38      70     145
15  Page   F   31      67     135
16  Quin   M   29      71     176
17  Ruth   F   28      65     131

In [ ]:
filtered_df = df2[(df2['Age'] > 10) & (df2['Height'] < 70)]
print(filtered_df)

    Name Sex  Age  Height  Weigth
1   Bert   M   42      68     166
4   Elly   F   30      66     124
5   Fran   F   33      66     115
6   Gwen   F   26      64     121
9   Jake   M   32      69     143
10  Kate   F   47      69     139
12  Myra   F   23      62      98
15  Page   F   31      67     135
17  Ruth   F   28      65     131

In [ ]:
grouped_data = df2.groupby('Sex')
print(grouped_data)
grouped_data.count()

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x7bf8117f49a0>

     Name  Age  Height  Weigth
Sex
F       7    7       7       7
M      11   11      11      11

In [ ]:
df = pd.read_csv("biostatsD.csv")
df

    Name Gender  Age  Height  Weigth
0   Alex      M   41      74     170
1   Bert      M   42      68     166
2   Carl      M   32      70     155
3   Dave      M   39      72     167
4   Elly      F   30      66     124
5   Fran      F   33      66     115
6   Gwen      F   26      64     121
7   Hank      M   30      71     158
8   Ivan      M   53      72     175
9   Jake      M   32      69     143
10  Kate      F   47      69     139
11  Luke      M   34      72     163
12  Myra      F   23      62      98
13  Neil      M   36      75     160
14  Omar      M   38      70     145
15  Page      F   31      67     135
16  Quin      M   29      71     176
17  Ruth      F   28      65     131

In [ ]:
df_dummies = pd.get_dummies(df, columns=['Gender'])
print(df_dummies)

    Name  Age  Height  Weigth  Gender_F  Gender_M
0   Alex   41      74     170     False      True
1   Bert   42      68     166     False      True
2   Carl   32      70     155     False      True
3   Dave   39      72     167     False      True
4   Elly   30      66     124      True     False
5   Fran   33      66     115      True     False
6   Gwen   26      64     121      True     False
7   Hank   30      71     158     False      True
8   Ivan   53      72     175     False      True
9   Jake   32      69     143     False      True
10  Kate   47      69     139      True     False
11  Luke   34      72     163     False      True
12  Myra   23      62      98      True     False
13  Neil   36      75     160     False      True
14  Omar   38      70     145     False      True
15  Page   31      67     135      True     False
16  Quin   29      71     176     False      True
17  Ruth   28      65     131      True     False

In [ ]:
df_dummies = pd.get_dummies(df, columns=['Gender'])
print(df_dummies)

    Name  Age  Height  Weigth  Gender_F  Gender_M
0   Alex   41      74     170     False      True
1   Bert   42      68     166     False      True
2   Carl   32      70     155     False      True
3   Dave   39      72     167     False      True
4   Elly   30      66     124      True     False
5   Fran   33      66     115      True     False
6   Gwen   26      64     121      True     False
7   Hank   30      71     158     False      True
8   Ivan   53      72     175     False      True
9   Jake   32      69     143     False      True
10  Kate   47      69     139      True     False
11  Luke   34      72     163     False      True
12  Myra   23      62      98      True     False
13  Neil   36      75     160     False      True
14  Omar   38      70     145     False      True
15  Page   31      67     135      True     False
16  Quin   29      71     176     False      True
17  Ruth   28      65     131      True     False

In [ ]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
data=pd.read_csv("Data_for_Missing_Values.csv")
data.head(15)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [ ]:
data=data.dropna()
data

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
5   France  35.0  58000.0       Yes
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [ ]:
data.mean()

TypeError: Could not convert ['FranceSpainGermanySpainFranceFranceGermanyFrance' 'NoYesNoNoYesYesNoYes'] to numeric

In [ ]:
data.median()

In [ ]:
df=data.iloc[:,1:3].values
df